0:
  Column_name: Entry_Number
  Column_type: unique-id
1:
  Column_name: LVE_SeqID
  Column_type: unique-id
2:
  Allowed_values: LASSA SAMPLE,NEG H2O,GPC IVT,L IVT,POS HAZV
  Column_name: Sample_Catagory
  Column_type: text
3:
  Column_name: SampleID
  Column_type: text
4:
  Column_name: BNITM_SeqID
  Column_type: text
5:
  Column_name: Merged to LVE_SeqID
  Column_type: text
  is_referring_to: LVE_SeqID
6:
  Column_name: Merged_SeqID info
  Column_type: text
  is_referring_to: LVE_SeqID
  separation_character: _
7:
  Allowed_values: extract,zymo,sample,IVT,H2O
  Column_name: Process_started_from
  Column_type: text
8:
  Column_name: Process_started_from_LVESeqID
  Column_type: text
  is_referring_to: LVE_SeqID
9:
  Column_name: SeqID_Info
  Column_type: text
10:
  Column_name: Sample_project_category
  Column_type: text
11:
  Column_name: Additional_SampleID_Info
  Column_type: text
12:
  Allowed_values: plasma,H2O,IVT,cell culture
  Column_name: Sample_Type
  Column_type: text
13:
  Column_name: Database_PatientID
  Column_type: numeric
14:
  Column_name: Sampling_Date
  Column_type: date
15:
  Column_name: Sampling_Year
  Column_type: numeric
16:
  Allowed_values: LASV,HIV
  Column_name: Suspect_Virus
  Column_type: text
17:
  Column_name: Sample_Comments
  Column_type: text
18:
  Column_name: Diagnostic_PCR_date
  Column_type: date
19:
  Column_name: "Diagnostic_PCR_volume-in-\xB5l"
  Column_type: numeric
20:
  Column_name: Diagnostic_PCR_LASV_GPC-Gene_Ct
  Column_type: numeric
21:
  Column_name: Diagnostic_PCR_LASV-L-Gene_Ct
  Column_type: numeric
22:
  Column_name: LabbookID
  Column_type: text
23:
  Column_name: Experiment_Brief_Descriptive_Title
  Column_type: text
24:
  Column_name: ConditionID
  Column_type: text
25:
  Allowed_values: single elute,multiple elutes combined
  Column_name: Condition_Tested
  Column_type: text
26:
  Allowed_values: Yes,yes,YES
  Column_name: Dilution_series
  Column_type: text
27:
  Column_name: BNITM_EXT_SeqID
  Column_type: text
  is_referring_to: BNITM_SeqID
28:
  Column_name: EXT_ProtocolID
  Column_type: text
29:
  Column_name: EXT_Protocol_Version
  Column_type: text
30:
  Allowed_values: QIAamp Viral RNA Mini Kit
  Column_name: EXT_kit
  Column_type: text
31:
  Column_name: Extraction_kit_lot
  Column_type: text
32:
  Column_name: Extraction_date
  Column_type: date
33:
  Column_name: "Extraction_sample-volume-in-\xB5l"
  Column_type: numeric
34:
  Column_name: "Elution_volume-in-\xB5l"
  Column_type: numeric
35:
  Column_name: Extraction_comments
  Column_type: text
36:
  Column_name: BNITM_EXT_PCR_date
  Column_type: date
37:
  Column_name: "BNITM_EXT_PCR_input-volume-GPC-gene-in-\xB5l"
  Column_type: numeric
38:
  Column_name: BNITM_EXT_PCR_LASV-GPC-Gene_Ct
  Column_type: numeric
39:
  Column_name: "BNITM_EXT_PCR_input-volume-L-gene-in-\xB5l"
  Column_type: numeric
40:
  Column_name: BNITM_EXT_PCR_LASV-L-Gene_Ct
  Column_type: numeric
41:
  Column_name: "BNITM_EXT_PCR_HASV-input-volume-in-\xB5l"
  Column_type: numeric
42:
  Column_name: BNITM_EXT_PCR_HAZV_Ct
  Column_type: numeric
43:
  Column_name: KUL_EXT_Worksheet_filename
  Column_type: text
44:
  Column_name: KUL_EXT_PCR_filename
  Column_type: text
  unique_with: KUL_EXT_PCR_SeqID-in-file
45:
  Column_name: KUL_EXT_PCR_SeqID-in-file
  Column_type: text
  unique_with: KUL_EXT_PCR_filename
46:
  Column_name: KUL_EXT_PCR_SeqID-original-sample
  Column_type: text
  is_referring_to: LVE_SeqID
47:
  Column_name: KUL_EXT_PCR_date
  Column_type: date
48:
  Column_name: "KUL_EXT_PCR1_input-volume-in-\xB5l"
  Column_type: numeric
49:
  Column_name: KUL_Extraction_PCR1_LASV-GPC-Gene_Ct
  Column_type: numeric
50:
  Column_name: KUL_Extraction_PCR1_LASV-L-Gene_Ct
  Column_type: numeric
51:
  Column_name: "KUL_Extraction_PCR2_input-volume-in-\xB5l"
  Column_type: numeric
52:
  Column_name: KUL_Extraction_PCR2_LASV_GPC-Gene_Ct
  Column_type: numeric
53:
  Column_name: KUL_Extraction_PCR2_LASV-L-Gene_Ct
  Column_type: numeric
54:
  Column_name: KUL_Extraction_PCR_HASV_date
  Column_type: date
55:
  Column_name: "KUL_Extraction_PCR_HASV-input-volume-in-\xB5l"
  Column_type: numeric
56:
  Column_name: KUL_Extraction_PCR_HASV_Ct
  Column_type: numeric
57:
  Column_name: KUL_EXT_Bioanalyzer-RNA_filename
  Column_type: text
58:
  Column_name: KUL_EXT_Bioanalyzer-RNA_date
  Column_type: date
59:
  Column_name: "KUL_EXT_Bioanalyzer-RNA_in-pg/\xB5l"
  Column_type: numeric
60:
  Column_name: KUL_EXT_Bioanalyzer-RNA_RIN-number
  Column_type: numeric
61:
  Column_name: KUL_EXT_comments bioanalyzer
  Column_type: text
62:
  Column_name: KUL_DNZ_worksheet_filename
  Column_type: text
63:
  Column_name: KUL_DNZ_Date
  Column_type: date
64:
  Column_name: KUL_DNZ_PCR_filename
  Column_type: text
  unique_with: KUL_DNZ_PCR_SeqID-in-file
65:
  Column_name: KUL_DNZ_PCR_SeqID-in-file
  Column_type: text
  unique_with: KUL_DNZ_PCR_filename
66:
  Column_name: KUL_DNZ_PCR_SeqID_original-sample
  Column_type: text
  is_referring_to: LVE_SeqID
67:
  Column_name: KUL_DNZ_PCR_date
  Column_type: date
68:
  Column_name: "KUL_DNZ_PCR_input-volume-in-\xB5l"
  Column_type: numeric
69:
  Column_name: KUL_DNZ_PCR_LASV_GPC-Gene_Ct
  Column_type: numeric
70:
  Column_name: KUL_DNZ_PCR_LASV_L-Gene_Ct
  Column_type: numeric
71:
  Column_name: "KUL_DNZ_PCR_HASV_input-volume-in-\xB5l"
  Column_type: numeric
72:
  Column_name: KUL_DNZ_PCR_HASV_Ct
  Column_type: numeric
73:
  Column_name: KUL_DNZ_Bioanalyzer-RNA_filename
  Column_type: text
74:
  Column_name: KUL_DNZ_Bioanalyzer-RNA_date
  Column_type: date
75:
  Column_name: "KUL_DNZ_Bioanalyzer-RNA_conc-in-pg/\xB5l"
  Column_type: numeric
76:
  Column_name: KUL_DNZ_Bioanalyzer-RNA_RIN-number
  Column_type: numeric
77:
  Column_name: KUL_lDNZ_comments-bioanalyzer
  Column_type: text
78:
  Column_name: KUL_CDN_worksheet _filename
  Column_type: text
79:
  Column_name: KUL_CDN_Date
  Column_type: date
80:
  Column_name: cDNA_PCR_file_name
  Column_type: text
  unique_with: cDNA_PCR_SeqID_in_file
81:
  Column_name: cDNA_PCR_SeqID_in_file
  Column_type: text
  unique_with: cDNA_PCR_file_name
82:
  Column_name: cDNA_PCR_SeqID_original_sample
  Column_type: text
  is_referring_to: LVE_SeqID
83:
  Column_name: cDNA_PCR_date
  Column_type: date
84:
  Column_name: cDNA_PCR_LASV_GPC_Gene
  Column_type: numeric
85:
  Column_name: cDNA_PCR_LASV_L_Gene
  Column_type: numeric
86:
  Column_name: cDNA_PCR_HASV
  Column_type: numeric
87:
  Column_name: KUL_CDN_Qubit_date
  Column_type: date
88:
  Column_name: "KUL_CDN_Qubit_conc-in-ng/\xB5l"
  Column_type: numeric
89:
  Column_name: KUL_CDN_Bioanalyzer-HSDNA_filename
  Column_type: text
90:
  Column_name: KUL_CDN_Bioanalyzer-HSDNA_date
  Column_type: date
91:
  Column_name: KUL_CDN_Bioanalyzer-HSDNA_Average-lengt-in-bp
  Column_type: numeric
92:
  Column_name: "KUL_CDN_Bioanalyzer-HSDNA_conc-in-pg/\xB5l"
  Column_type: numeric
93:
  Column_name: KUL_CDN_comments
  Column_type: text
94:
  Column_name: KUL_CDN_PCR_filename
  Column_type: text
  unique_with: KUL_CDN_PCR_SeqID-in-file
95:
  Column_name: KUL_CDN_PCR_SeqID-in-file
  Column_type: text
  unique_with: KUL_CDN_PCR_filename
96:
  Column_name: KUL_CDN_PCR_SeqID_original-sample
  Column_type: text
  is_referring_to: LVE_SeqID
97:
  Column_name: KUL_CDN_PCR_date
  Column_type: date
98:
  Column_name: "KUL_CDN_PCR_input-volume-in-\xB5l"
  Column_type: numeric
99:
  Column_name: KUL_CDN_PCR_LASV_GPC-Gene_Ct
  Column_type: numeric
100:
  Column_name: KUL_CDN_PCR_LASV_L-Gene_Ct
  Column_type: numeric
101:
  Column_name: "KUL_CDN_PCR_HASV_input-volume-in-\xB5l"
  Column_type: numeric
102:
  Column_name: KUL_CDN_PCR_HASV_Ct
  Column_type: numeric
103:
  Column_name: KUL_CDN_Comments
  Column_type: text
104:
  Column_name: KUL_LIB_worksheet _filename
  Column_type: text
105:
  Column_name: KUL_LIB_Date
  Column_type: date
106:
  Column_name: "KUL_LIB_cDNA-input-volume-in-\xB5l"
  Column_type: numeric
107:
  Column_name: "KUL_LIB_cDNA-TE-volume-added-in-\xB5l"
  Column_type: numeric
108:
  Column_name: KUL_LIB_incubation-time-fragmentation-in-min
  Column_type: numeric
109:
  Column_name: KUL_LIB_adaptor-dilution
  Column_type: numeric
110:
  Allowed_values: A3,B3,C3,D3,E3,F3,G3,H3,A5,B5,C5,D5,E5,F5,G5,H5
  Column_name: KUL_LIB_UMI-UDI-used
  Column_type: text
111:
  Column_name: KUL_LIB_cycles-during-PCR
  Column_type: numeric
112:
  Column_name: KUL_LIB_Qubit_date
  Column_type: date
113:
  Column_name: "KUL_LIB_Qubit_conc-in-ng/\xB5l"
  Column_type: numeric
114:
  Column_name: KUL_LIB_Bioanalyzer-HSDNA_filename
  Column_type: text
115:
  Column_name: KUL_LIB_Bioanalyzer-HSDNA_date
  Column_type: date
116:
  Column_name: KUL_LIB_Bioanalyzer-HSDNA_Average-lengt-in-bp
  Column_type: numeric
117:
  Column_name: "KUL_LIB_Bioanalyzer-HSDNA_conc-in-ng/\xB5l"
  Column_type: numeric
118:
  Column_name: KUL_KAPA_PCR_file_name
  Column_type: text
119:
  Column_name: KUL_KAPA_PCR_date
  Column_type: date
120:
  Column_name: KUL_KAPA_PCR_KQL-worksheet-file-name
  Column_type: text
  unique_with: KUL_KAPA_PCR_SeqID_in_file
121:
  Column_name: KUL_KAPA_PCR_SeqID_in_file
  Column_type: text
  unique_with: KUL_KAPA_PCR_KQL-worksheet-file-name
122:
  Column_name: KUL_KAPA_PCR_SeqID_original_sample
  Column_type: text
  is_referring_to: LVE_SeqID
123:
  Column_name: KUL_KAPA_PCR_Dil-1:1000-Ct1
  Column_type: numeric
124:
  Column_name: KUL_KAPA_PCR_Dil-1:1000-Ct2
  Column_type: numeric
125:
  Column_name: KUL_KAPA_PCR_Dil-1:8000-Ct1
  Column_type: numeric
126:
  Column_name: KUL_KAPA_PCR_Dil-1:8000-Ct2
  Column_type: numeric
127:
  Column_name: "KUL_KAPA_PCR_Total-yield-in-ng-\xB5l"
  Column_type: numeric
128:
  Column_name: "KUL_KAPA_PCR_Total-volume-in-\xB5l"
  Column_type: numeric
129:
  Column_name: KUL_KAPA_PCR_Total-yield-in-ng
  Column_type: numeric
130:
  Column_name: KUL_LIB_PCR_filename
  Column_type: text
  unique_with: KUL_LIB_PCR_SeqID-in-file
131:
  Column_name: KUL_LIB_PCR_SeqID-in-file
  Column_type: text
  unique_with: KUL_LIB_PCR_filename
132:
  Column_name: KUL_LIB_PCR_SeqID_original-sample
  Column_type: text
  is_referring_to: LVE_SeqID
133:
  Column_name: KUL_LIB_PCR_date
  Column_type: date
134:
  Column_name: "KUL_LIB_PCR_input-volume-in-\xB5l"
  Column_type: numeric
135:
  Column_name: KUL_LIB_PCR_LASV_GPC-Gene_Ct
  Column_type: numeric
136:
  Column_name: KUL_LIB_PCR_LASV_L-Gene_Ct
  Column_type: numeric
137:
  Column_name: "KUL_LIB_PCR_HASV_input-volume-in-\xB5l"
  Column_type: numeric
138:
  Column_name: KUL_LIB_PCR_HASV_Ct
  Column_type: numeric
